import { space, color } from "./config";
import theme from "./theme";

/**
 * Style Props tools
 *
 * WIP
 *
 * covert {mb: "36"} to {marginBottom: "var(--rh-space-36)"}
 * covert {color: "sprk.purple.deep"} to {color: "var(--rh-colors-sprk_purple_dark)"}
 */
export function getStylePropCssVar(propKey, propValue) {
  const allStyleProps = {
    ...space,
    ...color,
  };
  /**
   	1. check for propKey in allStyleProps
	2. grab the value of "scale" in matching object
	3. Validate that the value is in the theme using "scale" and "propValue"
	4. Valid value = isValidThemeValue(allStyleProps[propKey].scale, propValue)
	5. If valid, return new object
	{
		[allStyleProps.propKey.property]: getCSSVarFunctionString(allStyleProps[propKey].scale, propValue)
	}
 */
}

/**
 * Theme CSS var tools
 */

/**
 * Validates that a given themeKey and themeValueKey are found within the theme
 */
export function isValidThemeValue(themeKey, themeValueKey) {
  return !!theme?.[themeKey]?.[themeValueKey];
}

/**
 * Contains the "template" for generating CSS variables given a themeKey and themeValueKey
 * Returns a string
 */
export function getCSSVarName(themeKey, themeValueKey) {
  if (!isValidThemeValue(themeKey, themeValueKey)) return false;
  return `--rh-${themeKey}-${themeValueKey}`.replace(/\./gi, "_");
}

/**
 * Returns a value from the theme given a themeKey and themeValueKey
 */
export function getThemeValue(themeKey, themeValueKey) {
  if (!isValidThemeValue(themeKey, themeValueKey)) return false;
  const themeValue =
    typeof theme[themeKey][themeValueKey] === "object"
      ? theme[themeKey][themeValueKey].value
      : theme[themeKey][themeValueKey];
  return themeValue;
}

/**
 * Returns a CSS value - using CSS var function
 */
export function getCSSVarFunctionString(themeKey, themeValueKey) {
  if (!isValidThemeValue(themeKey, themeValueKey)) return false;
  const varName = getCSSVarName(themeKey, themeValueKey);
  return `--var(${varName})`;
}

/**
 * Return a string representing a CSS property/value. (using CSS var function)
 */
export function getThemeRuleCSSVarString(themeKey, themeValueKey) {
  if (!isValidThemeValue(themeKey, themeValueKey)) return false;

  const varName = getCSSVarName(themeKey, themeValueKey);
  const varValue = getThemeValue(themeKey, themeValueKey);

  return `${varName}: ${varValue};`;
}

/**
 * Returns an array of CSS variables generated by the theme
 */
export function getThemeCSSVars() {
  let cssVars = [];
  for (let themeKey in theme) {
    for (let themeValueKey in theme[themeKey]) {
      const rule = getThemeRuleCSSVarString(themeKey, themeValueKey);
      cssVars.push(rule);
    }
  }
  return cssVars;
}

/**
 * Playing around...
 */

const getErrorMessage = {
  invalidStylePropValue: (values) =>
    generateErrorMessage`Invalid value of ${values[0]} provided in ${values[1]}. Valid values are found in ${values[2]} in your theme.`,
};

const generateErrorMessage = (staticTags, ...tags) => {
  let str = [staticTags[0]];
  for (let i = 0; i < tags.length; i++) {
    str.push(tags[i] + staticTags[i + 1]);
  }
  return str.join("");
};

const consoleError = (errorType, values) => {
  const message = getErrorMessage[errorType](values);
};
